src/Entity/Tutorial.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

/**
 * @ORM\Entity(repositoryClass="App\Repository\TutorialRepository")
 * @Vich\Uploadable()
 */
class Tutorial
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $content;

    /**
     * @ORM\Column(type="datetimetz")
     */
    private $date_creation;

    /**
     * @var File|null
     * @Vich\UploadableField(mapping="tutorial_image", fileNameProperty="illustration")
     */
    private $imageFile;

    /**
     * @ORM\Column(type="string", length=500, nullable=true)
     */
    private $illustration;

    /**
     * @ORM\Column(type="boolean")
     */
    private $isPublished = 0;

    /**
     * @ORM\OneToMany(
     *     targetEntity="App\Entity\TutorialStep",
     *     mappedBy="tutorial",
     *     cascade={"persist", "remove"},
     *     orphanRemoval=true)
     */
    private $steps;

    /**
     * @ORM\OneToMany(
     *     targetEntity="App\Entity\Tool",
     *     mappedBy="tutorial",
     *     cascade={"persist", "remove"})
     */
    private $tools;

    /**
     * @ORM\ManyToOne(
     *     targetEntity="App\Entity\User",
     *     inversedBy="tutorials")
     * @ORM\JoinColumn(nullable=true)
     */
    private $author;


    public function __construct()
    {
        $this->steps = new ArrayCollection();
        $this->tools = new ArrayCollection();
    }
    
    public function getId(): ?int
    {
        return $this->id;
    }

    public function getAuthor(): ?User
    {
        return $this->author;
    }

    public function setAuthor(?User $author): self
    {
        $this->author = $author;

        return $this;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getDateCreation(): ?\DateTimeInterface
    {
        return $this->date_creation;
    }

    public function setDateCreation(\DateTimeInterface $date_creation): self
    {
        $this->date_creation = $date_creation;

        return $this;
    }

    public function getIllustration(): ?string
    {
        return $this->illustration;
    }

    public function setIllustration(?string $illustration): self
    {
        $this->illustration = $illustration;

        return $this;
    }

    public function getIsPublished(): ?bool
    {
        return $this->isPublished;
    }

    public function setIsPublished(bool $isPublished): self
    {
        $this->isPublished = $isPublished;

        return $this;
    }

    /**
     * @return Collection|TutorialStep[]
     */
    public function getSteps(): Collection
    {
        return $this->steps;
    }

    public function addStep(TutorialStep $step): self
    {
        if (!$this->steps->contains($step)) {
            $this->steps[] = $step;
            $step->setTutorial($this);
        }

        return $this;
    }

    public function removeStep(TutorialStep $step): self
    {
        if ($this->steps->contains($step)) {
            $this->steps->removeElement($step);
            // set the owning side to null (unless already changed)
            if ($step->getTutorial() === $this) {
                $step->setTutorial(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Tool[]
     */
    public function getTools(): Collection
    {
        return $this->tools;
    }

    public function addTool(Tool $tool): self
    {
        if (!$this->tools->contains($tool)) {
            $this->tools[] = $tool;
            $tool->setTutorial($this);
        }

        return $this;
    }

    public function removeTool(Tool $tool): self
    {
        if ($this->tools->contains($tool)) {
            $this->tools->removeElement($tool);

            if ($tool->getTutorial() == $this) {
                $tool->setTutorial(null);
            }
        }

        return $this;
    }

    /**
     * @return File|null
     */
    public function getImageFile() : ?File
    {
        return $this->imageFile;
    }

    /**
     * @param File|null $imageFile
     * @return $this
     * @throws \Exception
     */
    public function setImageFile(?File $imageFile = null)
    {
        $this->imageFile = $imageFile;

        if ($this->imageFile instanceof UploadedFile) {
            $this->date_creation = new \DateTime('now');
        }
        return $this;
    }
}

src/Form/TutorialType.php
<?php
namespace App\Form;

use App\Entity\Tutorial;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Validator\Constraints\File;

class TutorialType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('title', null, [
                'label' => 'Commence par donner un titre à ton tuto :'
            ])
            ->add('content', null, [
                'label' => 'Ajoute une courte description :'
            ])
            ->add('steps', CollectionType::class, [
                'label' => false,
                'entry_type' => TutorialStepType::class,
                'required' => false,
                'entry_options' => ['label' => false],
                'by_reference' => false,
                'allow_add' => true,
                'allow_delete' => true,
            ])
            ->add('is_published', ChoiceType::class, [
            'choices' => [
                'Oui' => true,
                'Non' => false,
                ],
            ])
            ->add('choix', ChoiceType::class, [
                'label' => 'Choisis le type d\'illustration que tu veux ajouter :',
                'mapped' => false,
                'choices' => [
                    'Une photo' => null,
                    'Une vidéo' => null,
                    'Pas d\'illustration' => null,
                ],
                'expanded' => true,
                'multiple' => false,
            ])
            ->add('illustration', null, [
                'required' => false,
                'label' => false,
                'attr' => [
                    'class' => 'champVid',
                    'style' => 'display: none;',
                    'placeholder' => 'Colle ici le lien vers ta vidéo Youtube !'
                ]
                ])
            ->add('imageFile', FileType::class, [
                'required'=> false,
                'label' => false,
                'attr' => [
                    'class' => 'champImg',
                    'placeholder' => 'Ajoute ta photo ! (elle ne doit pas dépasser 2Mo)',
                ],
                'constraints' => [
                    new File([
                        'mimeTypes' => [
                            'image/jpeg',
                            'image/png',
                        ],
                        'mimeTypesMessage' => 'Enregistre une image au format jpeg ou png',
                    ])
                ]
            ])
            ->add('tools', CollectionType::class, [
                'label' => false,
                'entry_type' => TutorialToolType::class,
                'required' => false,
                'entry_options' => ['label' => false],
                'by_reference' => false,
                'allow_add' => true,
                'allow_delete' => true,
            ]);
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Tutorial::class,
        ]);
    }
}

src/Controller/TutorialController.php
<?php

namespace App\Controller;

use App\Entity\Tutorial;
use App\Form\TutorialType;
use App\Repository\ToolRepository;
use App\Repository\TutorialRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/tutorial")
 */
class TutorialController extends AbstractController
{
    /**
     * @Route("/", name="tutorial_index", methods={"GET"})
     * @param TutorialRepository $tutorialRepository
     * @return Response
     */
    public function index(TutorialRepository $tutorialRepository): Response
    {
        $tuto = $tutorialRepository->findBy([
            'isPublished' => true,
        ]);

        return $this->render('tutorial/index.html.twig', [
            'tutorials' => $tuto,
        ]);
    }

    /**
     * @Route("/new", name="tutorial_new", methods={"GET","POST"})
     * @param Request $request
     * @param ToolRepository $toolRepository
     * @return Response
     * @throws \Exception
     */
    public function new(Request $request, ToolRepository $toolRepository): Response
    {
        $user = $this->getUser();

        if ($user) {
            $tutorial = new Tutorial();
            $tutorial->setAuthor($user);
            $form = $this->createForm(TutorialType::class, $tutorial);
            $form->handleRequest($request);

            if ($form->isSubmitted() && $form->isValid()) {
                $tutorial->setDateCreation(new \DateTime());
                if ($tutorial->getIllustration() != null) {
                    parse_str(parse_url($tutorial->getIllustration(), PHP_URL_QUERY), $link);
                    $tutorial->setIllustration($link['v']);
                }

                $entityManager = $this->getDoctrine()->getManager();
                $entityManager->persist($tutorial);
                $entityManager->flush();

                return $this->redirectToRoute('tutorial_show', [
                    'id' => $tutorial->getId(),
                ]);
            } else {
                return $this->render('tutorial/new.html.twig', [
                    'tutorial' => $tutorial,
                    'form' => $form->createView(),
                ]);
            }
        } else {
            $this->addFlash('danger', 'Tu dois être connecté pour déposer un tutoriel !');
            return $this->redirectToRoute('app_login');
        }
    }

    /**
     * @Route("/{id}", name="tutorial_show", methods={"GET"})
     * @param Tutorial $tutorial
     * @return Response
     */
    public function show(Tutorial $tutorial): Response
    {
        $tools = $tutorial->getTools();
        $handtools = [];
        $softwares = [];
        $hardwares = [];
        foreach ($tools as $key => $tool) {
            $category = $tool->getCategory();
            switch ($category) {
                case 'handtool':
                    array_push($handtools, $tool);
                    break;
                case 'software':
                    array_push($softwares, $tool);
                    break;
                case 'hardware':
                    array_push($hardwares, $tool);
                    break;
            }
        }
        return $this->render('tutorial/show.html.twig', [
            'tutorial' => $tutorial,
            'handtools' => $handtools,
            'softwares' => $softwares,
            'hardwares' => $hardwares,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="tutorial_edit", methods={"GET","POST"})
     * @param Request $request
     * @param Tutorial $tutorial
     * @param ToolRepository $toolRepository
     * @return Response
     */
    public function edit(Request $request, Tutorial $tutorial, ToolRepository $toolRepository)
    {
        $user = $this->getUser();

        if ($user) {
            if ($user->getId() == $tutorial->getAuthor()->getId()) {
                $form = $this->createForm(TutorialType::class, $tutorial);
                $form->handleRequest($request);

                if ($form->isSubmitted() && $form->isValid()) {
                    /*if ($form->getData()->getIllustration() != null) {
                        parse_str(parse_url($tutorial->getIllustration(), PHP_URL_QUERY), $link);
                        if ($link['v']) {
                            $tutorial->setIllustration($link['v']);
                        }
                    } */
                    $this->getDoctrine()->getManager()->flush();

                    return $this->redirectToRoute('tutorial_show', [
                        'id' => $tutorial->getId(),
                    ]);
                }

                return $this->render('tutorial/edit.html.twig', [
                    'tutorial' => $tutorial,
                    'form' => $form->createView(),
                ]);
            } else {
                $this->addFlash('danger', 'Tu ne peux pas accèder à cette page.');
                return $this->redirectToRoute('tutorial_show', [
                    'id' => $tutorial->getId(),
                ]);
            }
        } else {
            $this->addFlash('warning', 'Tu dois être connecté pour modifier un tutoriel !');
            return $this->redirectToRoute('app_login');
        }
    }

    /**
     * @Route("/{id}", name="tutorial_delete", methods={"DELETE"})
     * @param Request $request
     * @param Tutorial $tutorial
     * @return Response
     */
    public function delete(Request $request, Tutorial $tutorial): Response
    {
        if ($this->isCsrfTokenValid('delete'.$tutorial->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($tutorial);
            $entityManager->flush();
        }
        return $this->redirectToRoute('tutorial_index');
    }
}

templates/tutorial/_delete_form.html.twig
<form method="post" action="{{ path('tutorial_delete', {'id': tutorial.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ tutorial.id) }}">
    <button class="Supprimer">Delete</button>
</form>

templates/tutorial/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}
    Edition du Tuto !
{% endblock %}

{% block stylesheets %}
    {{ parent() }}
    {{ encore_entry_link_tags('tutoCreate') }}
{% endblock %}

{% block body %}
    <div class="container">
        <h1>Edition de ton Tuto !</h1>

        {{ form_start(form) }}
        {{ form_row(form.title, {'attr': {'placeholder': "Titre du Tutoriel"}}) }}
        {{ form_row(form.content, {'attr': {'placeholder': "Présentation"}}) }}
        <ol class="tools" data-prototype="{{ form_widget(form.tools.vars.prototype)|e('html_attr') }}">
            {% for tool in form.tools %}
                <hr>
                <li>
                    {{ form_row(tool.name, {'label': 'Le nom de ton outil'}) }}
                    {{ form_row(tool.quantity, {'label': 'La quantité'}) }}
                    {{ form_row(tool.category, {'label': 'Choisie la catégorie de ton outil'}) }}
                    <button class="remove-existing-tool btn btnRemoveTool">supprimer cette étape</button>
                </li>
            {% endfor %}
        </ol>
        <div class="tutoPresentation">{{ form_row(form.choix, {'attr': {'placeholder': "Choisis ton illustration :"}}) }}</div>
        {{ form_row(form.illustration) }}
        <div id="invisible">{{ form_row(form.imageFile, {'attr':{'data-browse':"Titre"}}) }}</div>
        <ol class="steps" data-prototype="{{ form_widget(form.steps.vars.prototype)|e('html_attr') }}">
            {% for step in form.steps %}
                <hr>
                <li>
                    {{ form_row(step.title, {'label': 'Titre de l\'étape'}) }}
                    {{ form_row(step.content, {'label': 'Description'}) }}
                    {{ form_row(step.imageFile, {'label': 'Ajoute une image'}) }}
                    <button class="remove-existing-step btn btnRemoveStep">supprimer cette étape</button>
                </li>
            {% endfor %}
        </ol>

        {{ form_row(form.is_published, {'label': 'Souhaites tu publier ton tuto ?'} ) }}

        <button class="btn btnCreateEdit" type="submit">
            Enregistrer les modifications
        </button>

        {{ form_end(form) }}
    </div>
{% endblock %}

{% block javascripts %}
    {{ parent () }}
    {{ encore_entry_script_tags('TutorialEditionForm') }}
    {{ encore_entry_script_tags('tool') }}
{% endblock %}

templates/tutorial/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste des Tutos{% endblock %}

{% block stylesheets %}
    {{ parent() }}
    {{ encore_entry_link_tags('tutorial') }}
{% endblock %}

{% block body %}
    <h1 class="tutorialIndexH1">Voici les tutos !</h1>
    <p class="container tutorialIndexDescription">
        {% if not app.user %}
            Tu te trouves actuellement sur l'espace tuto, c'est ici que tu peux découvrir les derniéres créations de la communauté, tu souhaites créer un tuto et le partager ? Inscrit toi ou connecte toi pour y avoir accès !
        {% else %}
            Tu te trouves actuellement sur l'espace tuto, c'est ici que tu peux découvrir les derniéres créations de la communauté, tu peux également créer ton propre tuto en te rendant sur
            <a href="{{ path('user_show', {'id': app.user.id}) }}">ton espace personnel</a> !
        {% endif %}
    </p>
    <section id="tutorialIndex">
            <div class="row container">
                {% for tutorial in tutorials %}
                    <div class="card cardTutorial">
                        {% if tutorial.illustration != null %}
                        <img class="card-img-top" src="/images/tutorial/{{ tutorial.illustration }}" alt="Card image cap">
                        {% else %}
                        <img class="card-img-top" src="{{ asset('build/images/robotDefault.png') }}" alt="Card image cap">
                        {% endif %}
                        <div class="card-body">
                            <h2 class="card-title">{{ tutorial.title }}</h2>
                            <div class="metadata">Ecrit le {{ tutorial.dateCreation | date('d/m/Y') }} à {{ tutorial.dateCreation | date('H:i') }} </div>
                            <p class="card-text">{{ tutorial.content|slice(0, 50) ~ '...' }}</p>
                        </div>
                        <a href="{{ path('tutorial_show', {'id': tutorial.id}) }}" class="btn btnCard">Voir le tuto 👀</a>
                    </div>

                {% endfor %}
            </div>
    </section>
{% endblock %}

templates/tutorial/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}
    Nouveau Tuto !
{% endblock %}

{% block stylesheets %}
    {{ parent() }}
    {{ encore_entry_link_tags('tutoCreate') }}
{% endblock %}

{% block body %}
    <div class="container">
        <h1>Création d'un Tuto !</h1>

        {{ form_start(form) }}
        {{ form_row(form.title, {'attr': {'placeholder': "Titre du Tutoriel"}}) }}
        {{ form_row(form.content, {'attr': {'placeholder': "Présentation"}}) }}
        <ol class="tools" data-prototype="{{ form_widget(form.tools.vars.prototype)|e('html_attr') }}">
            {% for tool in form.tools %}
                <hr>
                <li>
                    {{ form_row(tool.name, {'label': 'Le nom de ton outil'}) }}
                    {{ form_row(tool.quantity, {'label': 'La quantité'}) }}
                    {{ form_row(tool.category, {'label': 'Choisie la catégorie de ton outil'}) }}
                    <button class="remove-existing-tool btn btnRemoveTool">supprimer cette étape</button>
                </li>
            {% endfor %}
        </ol>
        <div class="tutoPresentation">{{ form_row(form.choix, {'attr': {'placeholder': "Choisis ton illustration :"}}) }}</div>
        {{ form_row(form.illustration) }}
        <div id="invisible">{{ form_row(form.imageFile, {'attr':{'data-browse':"Titre"}}) }}</div>
        <ol class="steps" data-prototype="{{ form_widget(form.steps.vars.prototype)|e('html_attr') }}">
            {% for step in form.steps %}
                <hr>
                <li>
                    {{ form_row(step.title, {'label': 'Titre de l\'étape'}) }}
                    {{ form_row(step.content, {'label': 'Description'}) }}
                    {{ form_row(step.imageFile, {'label': 'Ajoute une image'}) }}
                    <button class="remove-existing-step btn btnRemoveStep">supprimer cette étape</button>
                </li>
            {% endfor %}
        </ol>

        {{ form_row(form.is_published, {'label': 'Souhaites tu publier ton tuto ?'} ) }}

        <button class="btn btnCreateEdit" type="submit">
                Ajouter un nouveau tutoriel
        </button>

        {{ form_end(form) }}
    </div>
{% endblock %}

{% block javascripts %}
    {{ parent () }}
    {{ encore_entry_script_tags('TutorialEditionForm') }}
    {{ encore_entry_script_tags('tool') }}
{% endblock %}

templates/tutorial/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}
    {{ tutorial.title }}
{% endblock %}

{% block stylesheets %}
    {{ parent() }}
    {{ encore_entry_link_tags('tutorial') }}
{% endblock %}

{% block body %}

    {% if app.user != null and tuto.author.id is defined %}
        {% if app.user.id == tuto.author.id %}
            <div class="row bouton">
            <button class="btn btnEdit"><a href="{{ path('tutorial_edit', {'id': tuto.id})  }}">Modifier mon tuto</a></button>
                <div class = "del">
                    <form method="post" action="{{ path('tuto_delete', {'id': tuto.id}) }}" onsubmit="return confirm('Tu es sûr de vouloir supprimer ton tutoriel ?');">
                        <input type="hidden" name="_method" value="DELETE">
                        <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ tuto.id) }}">
                        <button class="btn btnDel btnDel">Supprimer mon tutoriel</button>
                    </form>
                </div>
            </div>
        {% endif %}
    {% endif %}

    <div class="tutoPresentation container">
        <h1 class="titleShow">{{ tutorial.title }}</h1>
        <article class="tutoContent">
            {% if tutorial.illustration is not null %}
                {% set ext = tutorial.illustration|split('.') %}
                {% if ext[1] is defined %}
                    <img class="imgTuto" src="/images/tutorial/{{ tutorial.illustration }}" >
                {% else %}
                    <iframe width="560" height="315" src="http://www.youtube.com/embed/{{ tutorial.illustration }}"></iframe>
                {% endif %}
            {% endif %}
            <p class="tutoText">
                {{ tutorial.content | raw }}
            </p>
        </article>
    </div>
    <div class="container">
        {% if tutorial.tools is not empty %}
            <div class="w-75 tool-box">
                <p>Pour réaliser ce tutoriel, tu auras besoin de :</p>
                <ul>
                    {% if handtools %}
                        <li>Outils :</li>
                        <ol>
                            {% for tool in handtools %}
                                <li>
                                    {{ tool.name }}
                                    {% if tool.quantity %}
                                        x{{ tool.quantity }}
                                    {% else %}
                                        x1
                                    {% endif %}
                                </li>
                            {% endfor %}
                        </ol>
                    {% endif %}
                    {% if hardwares %}
                        <li>Composants :</li>
                        <ol>
                            {% for tool in hardwares %}
                                <li>
                                    {{ tool.name }}
                                    {% if tool.quantity %}
                                        x{{ tool.quantity }}
                                    {% else %}
                                        x1
                                    {% endif %}
                                </li>
                            {% endfor %}
                        </ol>
                    {% endif %}
                    {% if softwares %}
                        <li>Logiciels :</li>
                        <ol>
                            {% for tool in softwares %}
                                <li>
                                    {{ tool.name }}
                                    {% if tool.quantity %}
                                        x{{ tool.quantity }}
                                    {% else %}
                                        x1
                                    {% endif %}
                                </li>
                            {% endfor %}
                        </ol>
                    {% endif %}
                </ul>
            </div>
        {% endif %}

        {% if tutorial.steps is not empty %}
            <ol>
                {% for step in tutorial.steps %}
                    <li>
                        <div class="customCollapse mt-4">
                            <div class="row">
                                <div class="col-6">
                                    <span>
                                        {{ step.title }}
                                    </span>
                                </div>
                                <div class="empty btn BtnCollapse col-4 col-sm-4 col-md-4 col-lg-5 col-xl-5"></div>
                                <button class="btn BtnCollapse col-2 col-sm-2 col-md-2 col-lg-1 col-xl-1" type="button">+</button>
                            </div>
                            <article class="contentCollapse">
                                <div class="row">
                                    {% if step.image is not null %}
                                        <p class="col-12 col-sm-12 col-md-8 col-lg-9 col-xl-10">
                                            {{ step.content }}
                                        </p>
                                        <img src="{{ asset('images/step/' ~ step.image) }}" alt="step_image" class="col-12 col-sm-12 col-md-4 col-lg-3 col-xl-2">
                                    {% else %}
                                        <p class="col-12 col-sm-12 col-md-12 col-lg-12 col-xl-12">
                                            {{ step.content }}
                                        </p>
                                    {% endif %}
                                </div>
                            </article>
                        </div>
                    </li>
                {% endfor %}
            </ol>
        {% endif %}
        <div class="metadata">
            <span>Créé le
            {{ tutorial.dateCreation | date('d/m/Y') }}
            par
            {{ tutorial.author ? tutorial.author.username : 'Anonyme' }}
            </span>
        </div>
    </div>
{% endblock %}

{% block javascripts %}
    {{ parent() }}
    {{ encore_entry_script_tags('tutorial') }}
{% endblock %}